server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/identity_service}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:1901}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signedKey: "9nnnr7oMmHq56BtkKDCPvGZz2KnkWuhmxelfxMacb9ZoW6vLAfXa/1PNq3l7LMmM"