server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/youtube_practice"
    username: root
    password: 1901
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signedKey: "9nnnr7oMmHq56BtkKDCPvGZz2KnkWuhmxelfxMacb9ZoW6vLAfXa/1PNq3l7LMmM"